local_backend: true

backend:
  name: git-gateway
  repo: gablemathias/gabematt-personal-blog
  branch: main

media_folder: "assets/uploads"  # Folder to store media like images
public_folder: "/images"  # Public folder path for media

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
    - label: 'About Page'
      name: 'about'
      file: 'about.markdown'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Body', name: 'body', widget: 'markdown' }